config/routes.rb
Kalefinder::Application.routes.draw do
  #root "pages#home"    
  #get "home", to: "pages#home", as: "home"
  #get "inside", to: "pages#inside", as: "inside"

  root "pages#home"

  devise_for :users

  resources :places do
    put 'score/:package_id', action: :score, on: :member, as: 'score'
  end

  resources :packages

  namespace :admin do
    root "base#index"
    resources :users
  end

end

app/models/place.rb
class Place < ActiveRecord::Base
  CATEGORIES = %w(fine_dining cajun_food creole_food cheap_food food cocktail_bar bar dive_bar live_music night_club shopping cafe zoo aquarium museum)
  has_many :scores, dependent: :delete_all
  has_many :packages, through: :scores

  serialize :categories, Array

  def score(package)
    val = scores.where(package_id: package.id).first.value * 20
    val
  end

end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  #before_action :authenticate_user!
  #before_action :auth
  before_action :set_place, only: [:show, :edit, :update, :destroy, :score]

  # GET /places
  # GET /places.json
  def index
    @places = Place.all
  end

  # GET /places/1
  # GET /places/1.json
  def show
  end

  # GET /places/new
  def new
    @place = Place.new
  end

  # GET /places/1/edit
  def edit
  end

  # POST /places
  # POST /places.json
  def create
    @place = Place.new(place_params)

    respond_to do |format|
      if @place.save
        format.html { redirect_to @place, notice: 'Place was successfully created.' }
        format.json { render action: 'show', status: :created, location: @place }
      else
        format.html { render action: 'new' }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1
  # PATCH/PUT /places/1.json
  def update
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to @place, notice: 'Place was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place.destroy
    respond_to do |format|
      format.html { redirect_to places_url }
      format.json { head :no_content }
    end
  end

  def score
    @place.scores.where(package_id: params[:package_id]).update_all(value: params.require(:score).permit(:value)[:value])
    redirect_to edit_place_path(@place), notice: 'Score updated.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def place_params
      params.require(:place).permit(:lat, :long, :short_name, :address, categories: [])
    end

    def auth
      authorize Place
    end
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/places/_form.html.erb
<%= form_for(@place) do |f| %>
  <% if @place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@place.errors.count, "error") %> prohibited this place from being saved:</h2>

      <ul>
      <% @place.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :lat %><br>
    <%= f.text_field :lat %>
  </div>
  <div class="field">
    <%= f.label :long %><br>
    <%= f.text_field :long %>
  </div>
  <div class="field">
    <%= f.label :short_name %><br>
    <%= f.text_field :short_name %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :categories %><br>
    <%= f.select :categories, Place::CATEGORIES, {}, :multiple => true %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/places/edit.html.erb
<h1>Editing place</h1>

<%= render 'form' %>

<% @place.scores.each do |score| %>
  <% if score.package %>
    <%= form_for score, url: score_place_path(@place, score.package_id), method: :put do |f| %>
      <%= f.label "#{score.package.name}'s score" %>
      <%= f.text_field :value %>
      <%= f.submit %>
    <% end %>
  <% end %>
<% end %>

<%= link_to 'Show', @place %> |
<%= link_to 'Back', places_path %>

app/views/places/index.html.erb
<h1>Listing places</h1>

<table>
  <thead>
    <tr>
      <th>Short name</th>
      <th>Address</th>
      <th>Categories</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @places.each do |place| %>
      <tr>
        <td><%= place.short_name %></td>
        <td><%= place.address %></td>
        <td><%= place.categories %></td>
        <td><%= link_to 'Edit', edit_place_path(place) %></td>
        <td><%= link_to 'Destroy', place, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Place', new_place_path %>

app/views/places/new.html.erb
<h1>New place</h1>

<%= render 'form' %>

<%= link_to 'Back', places_path %>

app/views/places/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Lat:</strong>
  <%= @place.lat %>
</p>

<p>
  <strong>Long:</strong>
  <%= @place.long %>
</p>

<p>
  <strong>Short name:</strong>
  <%= @place.short_name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @place.address %>
</p>

<p>
  <strong>Categories:</strong>
  <%= @place.categories %>
</p>

<%= link_to 'Edit', edit_place_path(@place) %> |
<%= link_to 'Back', places_path %>